# Generated by Django 3.0.5 on 2020-04-15 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecu',
            fields=[
                ('identifier', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('public_key', models.TextField()),
                ('primary', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('identifier', models.CharField(max_length=17, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ecu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='director.Ecu')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='image.ImageTarget')),
            ],
        ),
        migrations.AddField(
            model_name='ecu',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='director.Vehicle'),
        ),
    ]
