# Generated by Django 3.0.5 on 2020-04-14 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('identifier', models.CharField(max_length=17, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ecu',
            fields=[
                ('identifier', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('public_key', models.TextField()),
                ('cryptography_method', models.CharField(max_length=16)),
                ('primary', models.BooleanField()),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='director.Vehicle')),
            ],
        ),
    ]
