# Generated by Django 3.0.5 on 2020-04-14 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecu',
            name='cryptography_method',
        ),
    ]
